language: python
python:
  - 3.5
  - 3.6
  - 3.7

jobs:
  include:
    - stage: "Lint"
      install:
        - pip install -r REQUIREMENTS.txt
        - pip install pylint mypy
      name: "Pylint"
      script: pylint discirc
      - name: "Mypy"
      script: mypy discirc
